### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [horizontalsystems/ethereum-kit-android#112]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by Neustradamus** [comment]
@omurovch: Thanks but it is always here :/
- https://github.com/horizontalsystems/ethereum-kit-android/search?q=spongycastle&unscoped_q=spongycastle

**Comment by omurovch** [comment]
> @omurovch: Thanks but it is always here :/
> 
> * https://github.com/horizontalsystems/ethereum-kit-android/search?q=spongycastle&unscoped_q=spongycastle

@Neustradamus oh, my bad. forgot to check tests :(

**Comment by Neustradamus** [comment]
@omurovch: Perfect, thanks :)
