### ISSUE TITLE
Fix double spend on eth based networks

### ISSUE THREAD

**Issue by mNizhurin** [horizontalsystems/ethereum-kit-android#131]
Track and increase nonce for outgoing transactions.

Nonce provider can give same nonce when it's already used in other transaction. This leads to double spend or transaction drop-replace https://info.etherscan.com/transaction-dropped-replaced/.

**Comment by esengulov** [comment]
Issue Merged Into # https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2565
