### ISSUE TITLE
Custom token swipe is not working

### ISSUE THREAD

**Issue by navneetboghani** [horizontalsystems/ethereum-kit-android#201]
My token address is 0x2c8aec2fd0c0feba71e0424873461908067d5bf4. when I swipe token from ETH to SHUBH (SHUBH), it show error pair is not found. but we have provide liquidity from SHUBH (SHUBH) to ETH in uniswape. 
![Screenshot_20211009-230240_Erium Wallet](https://user-images.githubusercontent.com/3005403/137104553-56722383-c935-4567-b719-ad96f0bfbf78.jpg)

**Comment by rafaelekol** [comment]
Resolved issue in direct chat.
